In [1]:
! pip install tensorflow

  Using cached tensorflow-2.18.0-cp312-cp312-win_amd64.whl.metadata (3.3 kB)
  Using cached tensorflow_intel-2.18.0-cp312-cp312-win_amd64.whl.metadata (4.9 kB)
  Using cached absl_py-2.1.0-py3-none-any.whl.metadata (2.3 kB)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
  Using cached gast-0.6.0-py3-none-any.whl.metadata (1.3 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
  Using cached termcolor-2.5.0-py3-none-any.whl.metadata (6.1 kB)
  Using cached grpcio-1.70.0-cp312-cp312-win_amd64.whl.metadata (4.0 kB)
  Using cached tensorboard-2.18.0-py3-none-any.whl.metadata (1.6 kB)
  Using cached keras-3.8.0-py3-none-any.whl.metadata (5.8 kB)
  Using cached ml_dtypes-0.4.1-cp312-cp312-win_amd64.whl.metadata (20 kB)
  Using cached namex-0.0.8-py3-none-any.whl.metadata (246 bytes)
  Using cached optre

In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d=tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_d=tf.constant([182,26,15,83,-129],dtype=tf.float32)
print(tensor_one_d )

tf.Tensor([ 182.   26.   15.   83. -129.], shape=(5,), dtype=float32)


In [5]:
tensor_two_d=tf.constant([
    [2,94,-26],
    [3,10,-56],
    [3,10,-47],
    [0,2,-4]
    ])
print(tensor_two_d)

tf.Tensor(
[[  2  94 -26]
 [  3  10 -56]
 [  3  10 -47]
 [  0   2  -4]], shape=(4, 3), dtype=int32)


In [6]:
tensor_three_d=tf.constant([
    [[2,20,3],
     [3,4,5]],
    [[4,78,6],
     [5,46,7]],
    [[6,103,8],
    [7,8,999]],
])
print(tensor_three_d)

tf.Tensor(
[[[  2  20   3]
  [  3   4   5]]

 [[  4  78   6]
  [  5  46   7]]

 [[  6 103   8]
  [  7   8 999]]], shape=(3, 2, 3), dtype=int32)


In [7]:
print(tensor_three_d.shape)

(3, 2, 3)


In [8]:
print(tf.shape(tensor_three_d))

tf.Tensor([3 2 3], shape=(3,), dtype=int32)


In [9]:
print(tensor_three_d.ndim)

3


In [10]:
tensor_four_d = tf.constant([
[
    [[1,72,3],
     [3,4,59]],
    [[96,5,6],
     [5,6,32]],
    [[6,7,8],
    [7,13,9]],],

  [
    [[11,12,13],
     [3,42,5]],
    [[14,15,16],
     [5,16,7]],
    [[96,17,18],
    [7,48,9]],],

 [
    [[33,11,58],
     [3,42,59]],
    [[4,5,6],
     [5,16,87]],
    [[96,7,98],
    [7,48,93]],],
])
print(tensor_four_d)

tf.Tensor(
[[[[ 1 72  3]
   [ 3  4 59]]

  [[96  5  6]
   [ 5  6 32]]

  [[ 6  7  8]
   [ 7 13  9]]]


 [[[11 12 13]
   [ 3 42  5]]

  [[14 15 16]
   [ 5 16  7]]

  [[96 17 18]
   [ 7 48  9]]]


 [[[33 11 58]
   [ 3 42 59]]

  [[ 4  5  6]
   [ 5 16 87]]

  [[96  7 98]
   [ 7 48 93]]]], shape=(3, 3, 2, 3), dtype=int32)


In [11]:
import numpy as np

In [12]:
np_array=np.array([1,2,3])
print (np_array)

[1 2 3]


In [13]:
converted_tensor = tf.convert_to_tensor(np_array)

In [14]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [15]:
print(eye_tensor*3)

tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float32)


In [16]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[ True False False]
 [False  True False]
 [False False  True]], shape=(3, 3), dtype=bool)


In [17]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=3,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [18]:
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(3, 5, 5), dtype=float32)


In [19]:

eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[3,4],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]]


 [[[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 0. 0. 1. 0.]
   [0. 0. 0. 0. 1.]]

  [[1. 0. 0. 0. 0.]
   [0. 1. 0. 0. 0.]
   [0. 0. 1. 0. 0.]
   [0. 

In [21]:
fill_tensor = tf.fill(

    [1,3,4],5,name=None
)
print (fill_tensor)

tf.Tensor(
[[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]], shape=(1, 3, 4), dtype=int32)


In [22]:
ones_tensor=tf.ones(
    [5,3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]], shape=(5, 3, 2), dtype=float32)


In [23]:
one_like_tensor=tf.ones_like(fill_tensor)
print (one_like_tensor)

tf.Tensor(
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]], shape=(1, 3, 4), dtype=int32)


In [24]:
zeros_tensor=tf.zeros(
    [3,2],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [25]:
t=tf.constant([[[1,1,1],[2,2,2],[3,3,3],[4,4,4]]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [26]:
t=tf.constant([[[1,1,1],[2,2,2]]])
tf.size(t,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [28]:
random_tensor=tf.random.normal(
    
    [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

print(random_tensor)

tf.Tensor(
[[ 1.6234066  -0.03368912]
 [ 0.25068972  0.8024162 ]
 [ 0.19329672 -0.9280327 ]], shape=(3, 2), dtype=float32)
